### ISSUE TITLE
Memory Leak on error

### ISSUE THREAD

**Issue by stacksmith** [Robert-van-Engelen/tinylisp#13]
Every time an unknown token is entered in REPL, an ERR is indicated and the free cell count is one less than before!
```
tinylisp
930>asf
ERR
929>asfd
ERR
928>1
1
928>(nil)
ERR
928>
```
Note that an ERR without a bad token does not lose memory...

**Comment by Robert-van-Engelen** [comment]
Atom names are never released from memory. They are stacked each time a new atom is created, which is explained in the article. Not a problem, since a program has a limited and fixed number of atom names anyway. Some early lisp implementatations did the same, as well as more modern Prolog interpreters like SWI-Prolog, which never released atoms until more recently.

**Comment by stacksmith** [comment]
Thank you, I suspected as much.  The GC implementation is very interesting indeed.
