### ISSUE TITLE
Recursion bug?

### ISSUE THREAD

**Issue by RyanBurnside** [Robert-van-Engelen/tinylisp#16]
Hello, first let me thank you for a wonderful tutorial on how Lisp may be minimally implimented.
The PDF is excellent and I'm having a great time learning what might otherwise be thousands of lines of code.

I did note that there may be a bug when calling the function below:
`(define foo (lambda (v val)
              (if (= v 10)
                  val
                  (foo (+ v 1) (+ val 1 )))))`

When called with (foo 0 100) I get 100 back.

However, in Scheme and Common Lisp (adjusted) I get 110 back.

![Screenshot_2024-06-25_00-05-07](https://github.com/Robert-van-Engelen/tinylisp/assets/1874759/592d7fe3-ef84-4149-a8f9-188e8d678a76)

**Comment by Robert-van-Engelen** [comment]
This is because `=` is not defined. It is defined in `init.lisp` as:
```lisp
(define = (lambda (x y) (eq? (- x y) 0)))
```
See the PDF how `init.lisp` can be parsed when starting tinylisp, which requires minimal changes.

Otherwise, you example works fine with `eq?`:
```lisp
930>(define foo (lambda (v val) (if (eq? v 10) val (foo (+ v 1) (+ val 1 )))))          
foo
872>(foo 0 100)
110
872>
```
Note that error reporting is pretty much absent in tinylisp. So the fact that `=` is not defined is just the value `ERR`:
```lisp
930>(= 1 1)
ERR
```
This is considered false, hence the 100 you get.

Error reporting and exceptions and so on are described in the PDF.
